### ISSUE TITLE
Where’s the Distro

### ISSUE THREAD

**Issue by mugman174** [Generic-Linux/Generic-Linux#1]
Someone upload the file

**Comment by caughtquick** [comment]
@caitcat is working on it, and said she's done with it. She hasn't been online for 17ish hours though so she'll probably put it on the Vps when she's done and has the time

**Comment by mugman174** [comment]
> @caitcat is working on it, and said she's done with it. She hasn't been online for 17ish hours though so she'll probably put it on the Vps when she's done and has the time

Ok



GitHub mobile is weak

**Comment by thewarsawpakt** [comment]
[check this out](https://pub.genericlinux.org)
