### ISSUE TITLE
Hello Generic Linux

### ISSUE THREAD

**Issue by mAsTa-TiVo** [Generic-Linux/Generic-Linux#2]
May I Join The Project? I Am An Perl Enthusiast And I Can Add Perl Code To The Website To Make It Better. I Can Also Write Good Python Code.

**Comment by thewarsawpakt** [comment]
Do you have any repositories or code that I can see, perhaps as an example?

**Comment by mAsTa-TiVo** [comment]
No But I Am Good At It

**Comment by caughtquick** [comment]
Proof? credentials of any sort, example code, anything

**Comment by videotoaster** [comment]
sorry mate but if you don't have any examples of your excellent perl we can't verify that you're great at perl

**Comment by mugman174** [comment]
@mAsTa-TiVo send a hello world program in code brackets like this:
\```
your_code_here()
\```
```
your_code_here()
```
make a simple calculator in python and/or perl (make an add and subtract thing)

**Comment by mAsTa-TiVo** [comment]
Perl Code
```perl
$Number = 1;
$Other = 1;
$Add = $Number + $Other;
print '$add\r\n';
```
Python
```
Number = 1
Other = 1
Add = Number + Other
print(Add)
```

**Comment by mugman174** [comment]
no it has to add and subtract

**Comment by mugman174** [comment]
and get input from user too

**Comment by thewarsawpakt** [comment]
We use discord as the primary form of communication for out developer team, here is the [link](https://discord.gg/ukfHSh8U)

**Comment by caughtquick** [comment]
we are not being demeaning its just that the project is new and we don't want to trolls to have access

**Comment by mAsTa-TiVo** [comment]
Open The Issue Please And Also I Dont Use DIscord Because Pedos On Discord Do You Use Gitter

**Comment by thewarsawpakt** [comment]
Apologies, we have decided on discord.

**Comment by mAsTa-TiVo** [comment]
Please Use Gitter Its Good

**Comment by thewarsawpakt** [comment]
We don't have any intention of switching. I can confirm we do not have any pedophiles in our community.

**Comment by mAsTa-TiVo** [comment]
Discord Is Run By Pedos

**Comment by thewarsawpakt** [comment]
I'm not in the mood at the moment to discuss conspiracy theories.

**Comment by videotoaster** [comment]
can you just not @mAsTa-TiVo 
we do have an alternative set up and it is bridged to discord if you're interested

**Comment by caughtquick** [comment]
its called matrix so you don't have to use discord, we can give you the room(s) link so you don't have to use discord

**Comment by caughtquick** [comment]
also if you have a functional reason to use a different platform then explain to us why, not some conspiracy

**Comment by mugman174** [comment]
> Discord Is Run By Pedos

no u

**Comment by mugman174** [comment]
[https://genericlinux.org/community/channels.html](Choose one method of communication from this link: https://genericlinux.org/community/channels.html)

**Comment by thewarsawpakt** [comment]
I'm reopening this because we have decided on a solution. Please submit a pull request that contributes to any one of our projects, as part of your application.

**Comment by mugman174** [comment]
@mAsTa-TiVo

**Comment by videotoaster** [comment]
muggy why'd you mention him

**Comment by videotoaster** [comment]
ya got caught impersonating the GL project, so no, you aren't welcome
